development:
  adapter: sqlserver
  encoding: utf8
  database: consumer_api_development
  username: SA
  password: <YourStrong@Passw0rd>
  host: localhost
  port: 1433
  pool: 5

test:
  adapter: sqlserver
  encoding: utf8
  database: consumer_api_test
  username: SA
  password: <YourStrong@Passw0rd>
  host: localhost
  port: 1433
  pool: 5

production:
  adapter: sqlserver
  encoding: utf8
  database: consumer_api_production
  username: SA
  password: <%= ENV["CONSUMER_API_DATABASE_PASSWORD"] %>
  host: localhost
  port: 1433
  pool: 5
